name: django_docker
on:
  push:
    branches:
      - master
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Check codestyle
        run: pycodestyle ./demopages/*.py
      - name: Tests
        run: python manage.py test
build_and_pub:
  needs: [run_tests]
  runs-on: [ubuntu-latest]
  env:
    LOGIN: ${{ secrets.DOCKER_LOGIN }}
    NAME: ${{ secrets.DOCKER_NAME }}
  steps:
    - name: Login to docker
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-12345678Aa
    - uses: actions/checkout@master
    - name: Build image
      run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
    - name: Push image to docker
      run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
