name: django_docker
on:
  push:
    branches:
      - master
jobsa:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10.2
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Check codestyle
        run: pycodestyle ./demopages/*.py
      - name: Tests
        run: python manage.py test
